### ISSUE TITLE
Entity status updates requires periodic integration restart

### ISSUE THREAD

**Issue by ripple7511** [natekspencer/hacs-vivint#150]
### The problem

It seems that at least once a week, I find that automations relying on Vivint entities are no longer firing. Home Assistant is able to send commands (unlock doors, disarm/arm Vivint system, etc) but the status of all entities is not updated. Looking through my logs, this is the only thing I'm able to see:

Restarting the Vivint plugin always solves the issue.

### What version of Home Assistant Core are you running?

core-2024.10.3

### Anything in the logs that might be useful?

```txt
Logger: custom_components.vivint.hub
Source: helpers/update_coordinator.py:367
integration: Vivint (documentation, issues)
First occurred: October 18, 2024 at 11:55:06 PM (1 occurrences)
Last logged: October 18, 2024 at 11:55:06 PM

Error requesting vivint data: 500, message='Internal Server Error', url='https://www.vivintsky.com/api/authuser'
```

**Comment by ripple7511** [comment]
Adding more logs:
This error originated from a custom integration.

Logger: custom_components.vivint.hub
Source: helpers/update_coordinator.py:354
integration: Vivint (documentation, issues)
First occurred: 4:15:17 PM (1 occurrences)
Last logged: 4:15:17 PM

Unexpected error fetching vivint data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vivint/hub.py", line 80, in _async_update_data
    return await self.account.refresh()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vivintpy/account.py", line 153, in refresh
    await system.refresh()
  File "/usr/local/lib/python3.12/site-packages/vivintpy/system.py", line 59, in refresh
    system_data = await self.api.get_system_data(self.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vivintpy/vivintskyapi.py", line 156, in get_system_data
    resp = await self.__get(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vivintpy/vivintskyapi.py", line 570, in __get
    return await self.__call(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/vivintpy/vivintskyapi.py", line 654, in __call
    raise cls(message)
vivintpy.exceptions.VivintSkyApiError: Attempted to access an unauthorized Smarthome System

**Comment by ripple7511** [comment]
This follows immediately after:
This error originated from a custom integration.

Logger: custom_components.vivint.hub
Source: helpers/update_coordinator.py:367
integration: Vivint (documentation, issues)
First occurred: 4:10:17 PM (1 occurrences)
Last logged: 4:10:17 PM

Error requesting vivint data: 500, message='Internal Server Error', url='https://www.vivintsky.com/api/authuser'

**Comment by msherga** [comment]
I'm getting same behavior, but nothing in my logs about it. I see on my physical panel that my alarm gets successfully set, but then homeassistant doesn't see the status change until much later.

**Comment by nick2687** [comment]
I’m experiencing this issue as well, however there is nothing in my logs either. I use the door and motion sensors in several automations and after a period of time after a restart those automations no longer fire because Vivint stops communicating with home assistant.

Going to try and track down more information from my system, but just wanted to make sure you knew there were more people seeing this.

**Comment by ripple7511** [comment]
Got another error yesterday- this time bad gateway. 

Logger: custom_components.vivint.hub
Source: helpers/update_coordinator.py:367
integration: Vivint (documentation, issues)
First occurred: October 25, 2024 at 8:05:11 AM (2 occurrences)
Last logged: November 4, 2024 at 11:57:23 AM

Error requesting vivint data: 500, message='Internal Server Error', url='https://www.vivintsky.com/api/authuser'
Error requesting vivint data: 502, message='Bad Gateway', url='https://www.vivintsky.com/api/systems/3527906212567390?includerules=false'

**Comment by natekspencer** [comment]
My best guess right now is that when these server error / authentication issues happen, it somehow terminates the connection with pubnub for push updates to the component, which then introduces the lag. I haven't had a chance to test that theory though, or to test a fix that would try to resubscribe yet.

**Comment by Ljiddou** [comment]
I’m having the same issue where it’s taking a long time for automations to fire and state to update on home assistant. Sending a command like arming and disarming instantly updates the pens but opening/closing doors or windows takes 3-4 minutes to update on home assistant and I have to constantly reload to have it work normally.

**Comment by Ljiddou** [comment]
> I’m having the same issue where it’s taking a long time for automations to fire and state to update on home assistant. Sending a command like arming and disarming instantly updates the panel but opening/closing doors or windows takes 3-4 minutes to update on home assistant and I have to constantly reload to have it work normally.

I was able to set an automation to reload the Vivint integration couple times a day to temporarily fix this issue but the annoying thing is the automation that Vivint used last gets triggered every time it reloads.

**Comment by ripple7511** [comment]
Issue occurred again for me today. I didn't have debugging logs enabled. I'll re-enable and see if I can capture anything new.

**Comment by rvalentin1974** [comment]
just installed onto home assistant today and I am able to see all equipment on my system, I also see the equipment on a secondary system tied to same username. trying to figure out how to remove secondary account

**Comment by jonahgcarpenter** [comment]
I've been having this same issue for a while, with no luck enabling debug logs to find out the real error behind it. For anyone with the same issue, I made a temporary automation that uses an input boolean to prevent the automation from triggering an endless loop. You will also need the config entry id for your Vivant integration to set this up. To find this, you can go to...

Settings -> Devices and Services -> Click on your Vivant integration -> Devices, and the config id will be at the end of the URL like this:

`config_entry=8f90282c32d7cd4a5766474f20023fbc`

Also make sure to replace the "1111" with your proper disarm code

```yaml
alias: temp vivant fix
description: ""
triggers:
  - trigger: event
    event_type: call_service
    event_data:
      domain: alarm_control_panel
      service: alarm_arm_away
      service_data:
        entity_id: alarm_control_panel.jonah_s_house
    id: arm away
  - trigger: event
    event_type: call_service
    event_data:
      domain: alarm_control_panel
      service: alarm_arm_home
      service_data:
        entity_id: alarm_control_panel.jonah_s_house
    id: arm home
  - trigger: event
    event_type: call_service
    event_data:
      domain: alarm_control_panel
      service: alarm_disarm
      service_data:
        entity_id: alarm_control_panel.jonah_s_house
        code: "1111"
    id: disarm
conditions:
  - condition: state
    entity_id: input_boolean.automation_lock
    state: "off"
actions:
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.automation_lock
    data: {}
choose:
  - conditions:
      - condition: trigger
        id: arm away
    sequence:
      - action: homeassistant.reload_config_entry
        target: {}
        data:
          entry_id: 8f90282c32d7cd4a5766474f20023fbc
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
      - device_id: fcf9af92908eef94cd40f7bd23803e74
        domain: alarm_control_panel
        entity_id: 1cd9825b11f678bdb90b3b6b6206d2a3
        type: arm_away
  - conditions:
      - condition: trigger
        id: arm home
    sequence:
      - action: homeassistant.reload_config_entry
        target: {}
        data:
          entry_id: 8f90282c32d7cd4a5766474f20023fbc
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
      - device_id: fcf9af92908eef94cd40f7bd23803e74
        domain: alarm_control_panel
        entity_id: 1cd9825b11f678bdb90b3b6b6206d2a3
        type: arm_home
  - conditions:
      - condition: trigger
        id: disarm
    sequence:
      - action: homeassistant.reload_config_entry
        target: {}
        data:
          entry_id: 8f90282c32d7cd4a5766474f20023fbc
      - delay:
          hours: 0
          minutes: 0
          seconds: 5
      - device_id: fcf9af92908eef94cd40f7bd23803e74
        domain: alarm_control_panel
        entity_id: 1cd9825b11f678bdb90b3b6b6206d2a3
        type: disarm
        code: "1111"
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.automation_lock
        data: {}
mode: single
```

hope this helps!
