### ISSUE TITLE
Regression with support for light brightness in 2023.3.1

### ISSUE THREAD

**Issue by GaryGSC** [natekspencer/hacs-vivint#96]
After updating from v2023.3.0 to v2023.3.1, my lights no longer support brightness controls.

State attributes for my can lights using [2023.3.0](https://github.com/natekspencer/hacs-vivint/releases/tag/2023.3.0):
```yml
supported_color_modes:
  - brightness
color_mode: brightness
brightness: 130
icon: mdi:light-recessed
friendly_name: Can Lights
supported_features: 1
```

State attributes for my can lights using [2023.3.1](https://github.com/natekspencer/hacs-vivint/releases/tag/2023.3.1):
```yml
supported_color_modes:
  - onoff
color_mode: onoff
icon: mdi:light-recessed
friendly_name: Can Lights
supported_features: 0
```

[This](https://github.com/natekspencer/hacs-vivint/pull/90/commits/7e73b05b72059a5b5026d05f97641e01f8e62732#diff-e774fa6591e922f8273d9ae96f6b6f21b1924aba222bda64803355629404e8e7L43-R41) appears to be the relevant code change.
